### ISSUE TITLE
Button "view project" translation

### ISSUE THREAD

**Issue by m-paniez9292** [individuart/work#5]
Hi,
A minor update in file individuart/work/components/worklist/default.htm : 
- categories (l6) :
`<div class="work-category selected" id="cat-0">all categories</div>`
in
`<div class="work-category selected" id="cat-0">{{'all categories'|_}}</div>`
- to have button translation (l 22) : 
`<a href="#view-work/{{work.id}}/{{ work.slug }}" class="work__button">view project</a>`
in
`<a href="#view-work/{{work.id}}/{{ work.slug }}" class="work__button">{{'view project'|_}}</a>`

You can update individuart/work/components/worklist/workdetail.htm too (l16) :
`<a class="work-detail__link" href="{{work.url}}" onclick="window.open(this.href);return false;">ir al proyecto</a>`
in
`<a class="work-detail__link" href="{{work.url}}" onclick="window.open(this.href);return false;">{{'ir al proyecto'|_}}</a>`

Now, you can make your translation in settings > Translate > Translate messages

Thanks

**Comment by individuart** [comment]
Hi.

If I change the files including twig translations tags the users that install my plugin and haven't  installed the RainLab Translate plugin will get an error.

Thanks for your comments
